/**
 * 覆盖层 UI 模板（HTML 与 CSS）
 * 方向 C：悬浮球模式 —— 右下角悬浮球 + 按需弹出小面板
 */
// Фон страницы теперь применяется динамически из настроек (см. background.js),
// через внутренний протокол cuckoo-asset:// — CSS-правило пустое, скрывает
// только базовый цвет под картинкой.

const OVERLAY_HTML = [
'<div id="cuckoo-overlay" class="cuckoo-overlay cuckoo-hidden">',
'  <div class="cuckoo-header">',
'    <span class="cuckoo-title">Cuckoo Code</span>',
'    <button id="cuckoo-btn-minimize" class="cuckoo-btn-icon" title="收起面板">×</button>',
'  </div>',
'  <div class="cuckoo-body">',
'    <div class="cuckoo-section cuckoo-project-dir-section">',
'      <div class="cuckoo-project-dir-row">',
'        <span class="cuckoo-label">当前项目目录</span>',
'        <button id="cuckoo-btn-change-dir" class="cuckoo-btn-change-dir" title="点击修改项目目录">🔄 修改</button>',
'      </div>',
'      <div id="cuckoo-project-dir-display" class="cuckoo-project-dir-display">',
'        <span class="cuckoo-dir-path">未选择</span>',
'      </div>',
'    </div>',
'    <div class="cuckoo-divider"></div>',
'    <div class="cuckoo-actions">',
'      <button id="cuckoo-btn-init" class="cuckoo-btn cuckoo-btn-primary">初始化项目</button>',
'      <button id="cuckoo-btn-window-manager" class="cuckoo-btn cuckoo-btn-secondary" title="管理窗口（新建/切换）">窗口管理</button>',
'      <button id="cuckoo-btn-mcp" class="cuckoo-btn cuckoo-btn-secondary" title="管理 MCP 工具">MCP</button>',
'    </div>',
'    <div class="cuckoo-actions">',
      '<button id="cuckoo-btn-gen-doc" class="cuckoo-btn cuckoo-btn-primary" title="让 AI 生成项目说明文档 (CUCKOO.md)">生成项目说明</button>',
'    </div>',
'    <div class="cuckoo-actions">',
'      <button id="cuckoo-btn-immersive" class="cuckoo-btn cuckoo-btn-secondary" title="切换为沉浸式交流模式">沉浸式交流</button>',
'    </div>',
'    <div class="cuckoo-actions">',
'      <button id="cuckoo-btn-manual-parse" class="cuckoo-btn cuckoo-btn-secondary" title="手动触发解析当前页面内容中的工具调用">手动解析</button>',
'    </div>',
'    <div class="cuckoo-divider"></div>',
'    <div class="cuckoo-section cuckoo-session-section">',
'      <div class="cuckoo-session-header">',
'        <span class="cuckoo-label">会话列表</span>',
'        <button id="cuckoo-btn-refresh-sessions" class="cuckoo-btn-refresh-sessions" title="刷新会话列表">🔄 刷新</button>',
'      </div>',
'      <div id="cuckoo-session-list" class="cuckoo-session-list">',
'        <div class="cuckoo-session-empty">暂无会话</div>',
'      </div>',
'    </div>',
'    <div class="cuckoo-divider"></div>',
'    <div class="cuckoo-section">',
'      <label class="cuckoo-label">发送延迟设置</label>',
'      <div style="display:flex;gap:8px;align-items:center;">',
'        <input id="cuckoo-delay-min" type="number" min="0" max="10000" step="100" value="2000" style="width:70px;background:var(--ck-code-bg);border:1px solid var(--ck-border);border-radius:6px;padding:4px 8px;color:var(--ck-text);font-size:12px;" />',
'        <span style="color:var(--ck-text-dim);font-size:12px;">至</span>',
'        <input id="cuckoo-delay-max" type="number" min="0" max="10000" step="100" value="4000" style="width:70px;background:var(--ck-code-bg);border:1px solid var(--ck-border);border-radius:6px;padding:4px 8px;color:var(--ck-text);font-size:12px;" />',
'        <span style="color:var(--ck-text-dim);font-size:12px;">ms</span>',
'      </div>',
'      <button id="cuckoo-btn-save-delay" class="cuckoo-btn-text" style="align-self:flex-end;">保存延迟设置</button>',
'    </div>',
'    <div class="cuckoo-divider"></div>',
'    <div class="cuckoo-section">',
'      <label class="cuckoo-label">检测到任务：<span id="cuckoo-task-status" class="cuckoo-task-status cuckoo-hidden"><span class="cuckoo-spinner"></span>执行中</span></label>',
'      <pre id="cuckoo-cmd-preview" class="cuckoo-cmd-preview">暂无</pre>',
'    </div>',
'    <div id="cuckoo-result-section" class="cuckoo-section cuckoo-hidden">',
'      <label class="cuckoo-label">执行结果：</label>',
'      <div id="cuckoo-result-status" class="cuckoo-result-status"></div>',
'      <pre id="cuckoo-result-output" class="cuckoo-result-output"></pre>',
'    </div>',
'    <div class="cuckoo-section">',
'      <details id="cuckoo-history">',
'        <summary class="cuckoo-label">历史记录</summary>',
'        <div id="cuckoo-history-list" class="cuckoo-history-list"></div>',
'        <button id="cuckoo-btn-clear" class="cuckoo-btn-text">清空历史</button>',
'      </details>',
'    </div>',
'  </div>',
'</div>',
'<div id="cuckoo-window-manager" class="cuckoo-window-manager cuckoo-hidden">',
'  <div class="cuckoo-wm-header">',
'    <span class="cuckoo-title">窗口管理</span>',
'    <button id="cuckoo-wm-close" class="cuckoo-btn-icon" title="关闭">×</button>',
'  </div>',
'  <div class="cuckoo-wm-body">',
'    <div class="cuckoo-actions">',
'      <button id="cuckoo-wm-new-window" class="cuckoo-btn cuckoo-btn-primary">新建窗口</button>',
'    </div>',
'    <div class="cuckoo-divider"></div>',
'    <div class="cuckoo-section">',
'      <div class="cuckoo-session-header">',
'        <span class="cuckoo-label">窗口列表</span>',
'        <button id="cuckoo-wm-refresh" class="cuckoo-btn-refresh-sessions" title="刷新窗口列表">🔄 刷新</button>',
'      </div>',
'      <div id="cuckoo-window-list" class="cuckoo-session-list">',
'        <div class="cuckoo-session-empty">暂无窗口</div>',
'      </div>',
'    </div>',
'  </div>',
'</div>',
'<div id="cuckoo-mcp-manager" class="cuckoo-window-manager cuckoo-hidden">',
'  <div class="cuckoo-wm-header">',
'    <span class="cuckoo-title">MCP 工具</span>',
'    <button id="cuckoo-mcp-close" class="cuckoo-btn-icon" title="关闭">×</button>',
'  </div>',
'  <div class="cuckoo-wm-body cuckoo-mcp-body">',
'    <div class="cuckoo-mcp-left">',
'      <div class="cuckoo-session-header">',
'        <span class="cuckoo-label">已配置</span>',
'        <button id="cuckoo-mcp-refresh" class="cuckoo-btn-refresh-sessions" title="刷新">🔄</button>',
'      </div>',
'      <div id="cuckoo-mcp-list" class="cuckoo-session-list">',
'        <div class="cuckoo-session-empty">暂无</div>',
'      </div>',
'    </div>',
'    <div class="cuckoo-mcp-right">',
'      <textarea id="cuckoo-mcp-json" class="cuckoo-cmd-preview cuckoo-mcp-json" rows="14" style="font-size:11px;" placeholder="{\n  \"mcpServers\": {\n    \"filesystem\": {\n      \"command\": \"npx\",\n      \"args\": [\"-y\", \"@modelcontextprotocol/server-filesystem\", \"C:/my-project\"]\n    }\n  }\n}"></textarea>',
'      <div class="cuckoo-actions">',
'        <button id="cuckoo-mcp-save" type="button" class="cuckoo-btn cuckoo-btn-primary">保存配置</button>',
'      </div>',
'    </div>',
'  </div>',
'</div>',
'<div id="cuckoo-status-badge" title="Cuckoo Code 运行中">',
'  <span id="cuckoo-status-dot"></span>',
'  <span class="cuckoo-fab-icon">C</span>',
'</div>',
'<div id="cuckoo-first-time-dialog" class="cuckoo-first-time-dialog cuckoo-hidden">',
'  <div class="cuckoo-first-time-box">',
'    <button id="cuckoo-btn-first-close" class="cuckoo-btn-icon cuckoo-first-time-close" title="关闭">×</button>',
'    <div class="cuckoo-first-time-text">首次创建对话时，需要初始化项目，并选择一个项目目录，不然无法使用</div>',
'    <div class="cuckoo-actions">',
'      <button id="cuckoo-btn-first-init" class="cuckoo-btn cuckoo-btn-primary">初始化项目</button>',
'    </div>',
'  </div>',
'</div>',
].join('\n');

const OVERLAY_CSS = [
':root {',
'  --ck-bg: rgba(17, 19, 34, 0.97);',
'  --ck-surface: rgba(255, 255, 255, 0.04);',
'  --ck-surface-hover: rgba(255, 255, 255, 0.08);',
'  --ck-border: rgba(255, 255, 255, 0.08);',
'  --ck-primary: #8b93ff;',
'  --ck-primary-strong: #6d76ff;',
'  --ck-text: #dde1ff;',
'  --ck-text-dim: #8a90b8;',
'  --ck-green: #4ade80;',
'  --ck-red: #ff6b7a;',
'  --ck-code-bg: rgba(0, 0, 0, 0.35);',
'}',
'.cuckoo-overlay {',
'  position: fixed; bottom: 84px; right: 24px; width: 300px; max-height: 60vh;',
'  background: rgba(17, 19, 34, 0.98);',
'  border: 1px solid var(--ck-border);',
'  border-radius: 16px;',
'  z-index: 2147483647;',
'  will-change: transform;',
'  display: flex; flex-direction: column;',
'  box-shadow: 0 12px 40px rgba(0, 0, 0, 0.45), 0 0 0 1px rgba(139, 147, 255, 0.06);',
'  transition: opacity 0.22s ease, transform 0.22s ease;',
'  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
'  color: var(--ck-text); font-size: 13px; line-height: 1.55;',
'  overflow: hidden;',
'}',
'.cuckoo-overlay.cuckoo-hidden { opacity: 0; pointer-events: none; transform: translateY(8px); }',
'.cuckoo-header {',
'  display: flex; align-items: center; justify-content: space-between;',
'  padding: 12px 16px 10px; flex-shrink: 0;',
'  border-bottom: 1px solid var(--ck-border);',
'  background: rgba(255, 255, 255, 0.02);',
'}',
'.cuckoo-title { font-size: 14px; font-weight: 700; color: #c8ccff; letter-spacing: 0.4px; }',
'.cuckoo-btn-icon {',
'  background: var(--ck-surface); border: 1px solid var(--ck-border); color: #8a90b8;',
'  cursor: pointer; font-size: 16px; width: 28px; height: 28px; border-radius: 8px;',
'  display: flex; align-items: center; justify-content: center; transition: all 0.2s;',
'  line-height: 1;',
'}',
'.cuckoo-btn-icon:hover { background: var(--ck-surface-hover); color: #fff; }',
'.cuckoo-body { padding: 12px 14px; overflow-y: auto; flex: 1; display: flex; flex-direction: column; gap: 12px; }',
'.cuckoo-section { display: flex; flex-direction: column; gap: 8px; }',
'.cuckoo-label { font-size: 11px; font-weight: 700; color: var(--ck-text-dim); text-transform: uppercase; letter-spacing: 1px; cursor: pointer; }',
'.cuckoo-cmd-preview {',
'  background: var(--ck-code-bg); border: 1px solid var(--ck-border);',
'  border-radius: 12px; padding: 10px 12px;',
'  font-family: "Cascadia Code", "Fira Code", "Consolas", monospace;',
'  font-size: 12px; color: #a7f3c0; line-height: 1.5;',
'  max-height: 140px; overflow: auto; white-space: pre-wrap; word-break: break-all; margin: 0;',
'}',
'.cuckoo-actions { display: flex; gap: 8px; width: 100%; }',
'.cuckoo-actions .cuckoo-btn { flex: 1 1 auto; }',
'.cuckoo-btn {',
'  flex: 1; padding: 9px 14px; border: 1px solid transparent; border-radius: 10px;',
'  font-size: 12.5px; font-weight: 600; cursor: pointer;',
'  transition: all 0.22s ease; letter-spacing: 0.3px;',
'}',
'.cuckoo-btn:active { transform: scale(0.98); }',
'.cuckoo-btn-primary {',
'  background: linear-gradient(135deg, #8b93ff, #6d76ff); color: #fff;',
'  box-shadow: 0 6px 18px rgba(109, 118, 255, 0.25);',
'}',
'.cuckoo-btn-primary:hover { box-shadow: 0 8px 22px rgba(109, 118, 255, 0.4); transform: translateY(-1px); }',
'.cuckoo-btn-primary:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }',
'.cuckoo-btn-secondary {',
'  background: var(--ck-surface); color: #c8ccff;',
'  border-color: var(--ck-border);',
'}',
'.cuckoo-btn-secondary:hover { background: var(--ck-surface-hover); color: #fff; border-color: rgba(139, 147, 255, 0.4); }',
'.cuckoo-btn-text {',
'  background: none; border: none; color: var(--ck-text-dim); padding: 4px 0;',
'  text-align: left; font-size: 11px; cursor: pointer; transition: color 0.2s;',
'}',
'.cuckoo-btn-text:hover { color: var(--ck-red); }',
'.cuckoo-result-status { font-size: 12px; font-weight: 600; padding: 2px 0; }',
'.cuckoo-result-status.success { color: var(--ck-green); }',
'.cuckoo-result-status.error { color: var(--ck-red); }',
'.cuckoo-result-output {',
'  background: var(--ck-code-bg); border: 1px solid var(--ck-border);',
'  border-radius: 12px; padding: 10px 12px;',
'  font-family: "Cascadia Code", "Fira Code", "Consolas", monospace;',
'  font-size: 11.5px; color: #c8ccff; line-height: 1.5;',
'  max-height: 200px; overflow: auto; white-space: pre-wrap; word-break: break-all; margin: 0;',
'}',
'.cuckoo-history-list { max-height: 140px; overflow-y: auto; display: flex; flex-direction: column; gap: 6px; }',
'.cuckoo-history-item {',
'  background: var(--ck-surface); border-radius: 10px; padding: 8px 10px;',
'  font-size: 12px; cursor: pointer; transition: background 0.2s;',
'}',
'.cuckoo-history-item:hover { background: rgba(139, 147, 255, 0.18); }',
'.cuckoo-history-item .cuckoo-cmd-text {',
'  font-family: "Consolas", monospace; color: #a7f3c0; font-size: 12px;',
'  display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;',
'}',
'.cuckoo-history-item .cuckoo-cmd-status { font-size: 11px; margin-top: 2px; display: block; }',
'.cuckoo-history-item .cuckoo-cmd-status.success { color: var(--ck-green); }',
'.cuckoo-history-item .cuckoo-cmd-status.error { color: var(--ck-red); }',
'.cuckoo-history-item .cuckoo-cmd-time { font-size: 10px; color: #5d6280; margin-top: 2px; display: block; }',
'#cuckoo-mcp-manager { width: 780px; max-width: 90vw; }',
'#cuckoo-mcp-manager .cuckoo-mcp-body { flex-direction: row; gap: 14px; align-items: stretch; overflow: hidden; }',
'.cuckoo-mcp-left { width: 220px; flex-shrink: 0; display: flex; flex-direction: column; }',
'.cuckoo-mcp-left .cuckoo-session-list { flex: 1; max-height: none; overflow-y: auto; }',
'.cuckoo-mcp-right { flex: 1; display: flex; flex-direction: column; gap: 10px; }',
'.cuckoo-mcp-json { flex: 1; min-height: 55vh; resize: vertical; }',
'.cuckoo-mcp-right .cuckoo-btn { flex: 0 0 auto; align-self: flex-start; }',
'.cuckoo-window-manager {',
'  position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);',
'  z-index: 2147483647; width: 520px; height: 80vh; max-height: 85vh;',
'  background: rgba(17, 19, 34, 0.98);',
'  border: 1px solid var(--ck-border); border-radius: 16px;',
'  display: flex; flex-direction: column; overflow: hidden;',
'  box-shadow: 0 16px 50px rgba(0, 0, 0, 0.55), 0 0 0 1px rgba(139, 147, 255, 0.08);',
'  transition: opacity 0.22s ease, transform 0.22s ease;',
'}',
'.cuckoo-window-manager.cuckoo-hidden { opacity: 0; pointer-events: none; transform: translate(-50%, -50%) scale(0.95); }',
'.cuckoo-wm-header {',
'  display: flex; align-items: center; justify-content: space-between;',
'  padding: 12px 16px 10px; flex-shrink: 0;',
'  border-bottom: 1px solid var(--ck-border);',
'  background: rgba(255, 255, 255, 0.02);',
'}',
'.cuckoo-wm-body { padding: 12px 14px; overflow: hidden; flex: 1; display: flex; flex-direction: column; gap: 12px; }',
'.cuckoo-window-item {',
'  display: flex; align-items: center; justify-content: space-between;',
'  background: var(--ck-surface); border: 1px solid var(--ck-border);',
'  border-radius: 10px; padding: 10px 12px; cursor: pointer;',
'  transition: background 0.2s; font-size: 12px;',
'  gap: 8px;',
'}',
'.cuckoo-window-item:hover { background: rgba(139, 147, 255, 0.18); }',
'.cuckoo-window-left { display: flex; align-items: center; gap: 6px; flex: 1; min-width: 0; }',
'.cuckoo-window-item .cuckoo-window-name { color: #c8ccff; font-weight: 600; flex-shrink: 0; }',
'.cuckoo-window-item .cuckoo-window-sep { color: #5d6280; flex-shrink: 0; }',
'.cuckoo-window-item .cuckoo-window-status { color: #8a90b8; font-size: 11px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'.cuckoo-window-del {',
'  color: #ff6b7a; cursor: pointer; font-size: 11px; padding: 2px 6px;',
'  border-radius: 6px; flex-shrink: 0; transition: all 0.2s;',
'}',
'.cuckoo-window-del:hover { background: rgba(255, 107, 122, 0.18); color: #fff; }',
'.cuckoo-window-item.active { border-color: rgba(139, 147, 255, 0.5); background: rgba(139, 147, 255, 0.12); }',
'#cuckoo-window-list { max-height: none; flex: 1; min-height: 200px; overflow-y: auto; }',
'#cuckoo-window-list .cuckoo-window-item { flex-shrink: 0; }',
'#cuckoo-status-badge {',
'  position: fixed; bottom: 24px; right: 24px; z-index: 2147483647;',
'  width: 48px; height: 48px; border-radius: 50%;',
'  background: rgba(139, 147, 255, 0.22); border: 1px solid rgba(139, 147, 255, 0.4);',
'  will-change: transform;',
'  display: flex; align-items: center; justify-content: center; gap: 0;',
'  cursor: pointer;',
'  transition: background 0.2s, border-color 0.2s, transform 0.15s;',
'}',
'#cuckoo-status-badge:hover { background: rgba(139, 147, 255, 0.35); border-color: rgba(139, 147, 255, 0.65); transform: scale(1.05); }',
'#cuckoo-status-dot {',
'  position: absolute; top: 6px; right: 6px;',
'  width: 9px; height: 9px; border-radius: 50%;',
'  background: var(--ck-green); animation: cuckoo-pulse 2s infinite;',
'}',
'.cuckoo-fab-icon {',
'  font-size: 22px; font-weight: 800; color: #a8afff; line-height: 1;',
'  user-select: none;',
'}',
'.cuckoo-toast {',
'  position: fixed; top: 18px; left: 50%; transform: translateX(-50%) translateY(-8px);',
'  z-index: 2147483648; min-width: 200px; max-width: 380px; text-align: center;',
'  background: rgba(22, 24, 44, 0.92); backdrop-filter: blur(18px);',
'  -webkit-backdrop-filter: blur(18px);',
'  border: 1px solid rgba(139, 147, 255, 0.28); border-radius: 12px;',
'  padding: 10px 16px; font-size: 13px; color: #dde1ff;',
'  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.35);',
'  opacity: 0; pointer-events: none; transition: opacity 0.22s ease, transform 0.22s ease;',
'}',
'.cuckoo-toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }',
'.cuckoo-task-status {',
'  display: inline-flex; align-items: center; gap: 5px;',
'  color: #a8afff; font-size: 11px; font-weight: 600;',
'}',
'.cuckoo-spinner {',
'  width: 11px; height: 11px; border-radius: 50%;',
'  border: 2px solid rgba(139,147,255,0.25); border-top-color: #8b93ff;',
'  animation: cuckoo-spin 0.8s linear infinite;',
'}',
'@keyframes cuckoo-spin { to { transform: rotate(360deg); } }',
'@keyframes cuckoo-pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.35; } }',
'@keyframes cuckoo-attention {',
'  0%, 100% { transform: scale(1); }',
'  10%, 30%, 50%, 70%, 90% { transform: scale(1.08); }',
'  20%, 40%, 60%, 80% { transform: scale(0.98); }',
'}',
'.cuckoo-btn-attention {',
'  animation: cuckoo-attention 1s ease-in-out 3;',
'  background: rgba(139, 147, 255, 0.35) !important;',
'  color: #fff !important;',
'  border-color: rgba(139, 147, 255, 0.6) !important;',
'}',
'.cuckoo-hidden { display: none !important; }',
'.cuckoo-home-mode .cuckoo-header .cuckoo-btn-icon,',
'.cuckoo-home-mode .cuckoo-body .cuckoo-section,',
'.cuckoo-home-mode .cuckoo-body .cuckoo-actions:not(:has(#cuckoo-btn-init)),',
'.cuckoo-home-mode .cuckoo-divider {',
'  display: none !important;',
'}',
'.cuckoo-overlay ::-webkit-scrollbar { width: 6px; }',
'.cuckoo-overlay ::-webkit-scrollbar-track { background: transparent; }',
'.cuckoo-overlay ::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.15); border-radius: 3px; }',
'.cuckoo-overlay ::-webkit-scrollbar-thumb:hover { background: rgba(255,255,255,0.25); }',
'.cuckoo-project-dir-section {',
'  background: var(--ck-surface); border-radius: 10px;',
'  padding: 8px 10px; border: 1px solid var(--ck-border);',
'}',
'.cuckoo-project-dir-row { display: flex; justify-content: space-between; align-items: center; }',
'.cuckoo-btn-change-dir {',
'  background: rgba(139,147,255,0.2); border: none;',
'  color: #a8afff; padding: 2px 8px; border-radius: 6px;',
'  cursor: pointer; font-size: 11px; font-weight: 600;',
'}',
'.cuckoo-btn-change-dir:hover { background: rgba(139,147,255,0.4); }',
'.cuckoo-project-dir-display { margin-top: 4px; font-size: 12px; font-family: "Consolas", monospace; color: #8a90b8; word-break: break-all; }',
'.cuckoo-dir-path { color: #a7f3c0; }',
'.cuckoo-divider { border-top: 1px solid var(--ck-border); margin: 2px 0; }',
'.cuckoo-session-section {',
'  background: var(--ck-surface); border-radius: 10px;',
'  padding: 8px 10px; border: 1px solid var(--ck-border);',
'}',
'.cuckoo-session-header { display: flex; justify-content: space-between; align-items: center; }',
'.cuckoo-btn-refresh-sessions {',
'  background: rgba(139,147,255,0.2); border: none;',
'  color: #a8afff; padding: 2px 8px; border-radius: 6px;',
'  cursor: pointer; font-size: 11px; font-weight: 600;',
'}',
'.cuckoo-btn-refresh-sessions:hover { background: rgba(139,147,255,0.4); }',
'.cuckoo-session-list { max-height: 100px; overflow-y: auto; margin-top: 4px; display: flex; flex-direction: column; gap: 4px; }',
'.cuckoo-session-item { background: rgba(255,255,255,0.05); border-radius: 8px; padding: 6px 10px; font-size: 12px; font-family: "Consolas", monospace; color: #ccc; cursor: pointer; transition: background 0.2s; }',
'.cuckoo-session-item:hover { background: rgba(139,147,255,0.2); }',
'.cuckoo-session-item .session-id { color: #a8afff; font-size: 11px; }',
'.cuckoo-session-item .session-action { color: #a7f3c0; font-size: 11px; font-weight: 600; }',
'.cuckoo-session-empty { color: #5d6280; font-size: 12px; font-style: italic; padding: 8px 0; text-align: center; }',
'.cuckoo-first-time-dialog {',
'  position: fixed; top: 0; left: 0; right: 0; z-index: 2147483647;',
'  display: flex; align-items: flex-start; justify-content: center;',
'  padding-top: 24px;',
'  pointer-events: none;',
'}',
'.cuckoo-first-time-dialog.cuckoo-hidden { display: none !important; }',
'.cuckoo-first-time-box {',
'  position: relative; max-width: 420px; width: 90%;',
'  background: rgba(17, 19, 34, 0.98);',
'  border: 1px solid rgba(139, 147, 255, 0.35);',
'  border-radius: 18px;',
'  padding: 28px 24px 22px;',
'  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.6), 0 0 0 1px rgba(139, 147, 255, 0.08);',
'  color: var(--ck-text); font-size: 14px; line-height: 1.6;',
'  text-align: center;',
'  pointer-events: auto;',
'}',
'.cuckoo-first-time-close { position: absolute; top: 10px; right: 10px; }',
'.cuckoo-first-time-text { margin-bottom: 18px; color: #dde1ff; }',
'.cuckoo-first-time-box .cuckoo-actions { justify-content: center; }',
'.cuckoo-first-time-box .cuckoo-btn { flex: 0 0 auto; min-width: 150px; }',
// ========== CSS-переменные (управляются из настроек Cuckoo Code) ==========
':root {',
'  --cuckoo-bg-blur: 0px;',           // размытие самой картинки фона
'  --cuckoo-header-blur: 12px;',      // стекло шапки
'  --cuckoo-sidebar-blur: 12px;',     // стекло сайдбара
'  --cuckoo-header-opacity: 45%;',    // плотность фона шапки (0 = прозрачно)
'  --cuckoo-sidebar-opacity: 45%;',   // плотность фона сайдбара (0 = прозрачно)
'  --cuckoo-toolblock-opacity: 55%;', // плотность фона tool-блоков
'  --cuckoo-toolblock-blur: 0px;',    // стекло tool-блоков
'}',
// ========== 页面背景：базовый цвет + стили (картинка ставится через JS) ==========
'html, body {',
'  background-color: #0f1220 !important;',
'  background-size: cover !important;',
'  background-position: center center !important;',
'  background-repeat: no-repeat !important;',
'  background-attachment: fixed !important;',
'}',
// ========== Размытие самой фоновой картинки (--cuckoo-bg-blur) ==========
// Отдельный fixed-слой поверх body, чтобы фильтр не затрагивал контент.
'html::before {',
'  content: "";',
'  position: fixed;',
'  inset: 0;',
'  background: inherit;',
'  background-image: inherit;',
'  background-size: cover;',
'  background-position: center center;',
'  background-attachment: fixed;',
'  filter: blur(var(--cuckoo-bg-blur));',
'  transform: scale(1.05);',  // скрываем размытые края по периметру
'  pointer-events: none;',
'  z-index: -1;',
'}',
// ========== 页面顶部标题栏毛玻璃（DeepSeek） ==========
// Прозрачность управляется переменной --cuckoo-header-opacity (0% — полностью прозрачно).
'.the-header {',
'  backdrop-filter: blur(var(--cuckoo-header-blur)) saturate(140%) !important;',
'  -webkit-backdrop-filter: blur(var(--cuckoo-header-blur)) saturate(140%) !important;',
'  background: rgba(15, 18, 32, var(--cuckoo-header-opacity)) !important;',
'}',
// ========== 去掉输入框底部的深色渐变，让背景图透出 ==========
// DeepSeek 在 _871cbca 与其空的子层 d72636e2 上画了从上到下的
// 线性渐变（底部是不透明的 rgb(21,21,23)），会挡住页面背景图。
// 用简写 background: transparent !important 一次清掉颜色+渐变。
'._871cbca,',
'._871cbca > .d72636e2 {',
'  background: transparent !important;',
'}',
// ========== 左侧边栏毛玻璃（DeepSeek） ==========
// .b8812f16.a2f3d50e — корень сайдбара. Внутри много слоёв, каждый со своим
// фоном (шапка _262baab, список _3586175/_6d215eb/_77cdc67, низ _7b40dad).
// Делаем прозрачными все промежуточные слои, чтобы стекло работало насквозь.
'.b8812f16.a2f3d50e,',
'.b8812f16.a2f3d50e > div,',
'.b8812f16.a2f3d50e > div > div,',
'.b8812f16.a2f3d50e ._262baab,',
'.b8812f16.a2f3d50e ._3586175,',
'.b8812f16.a2f3d50e ._6d215eb,',
'.b8812f16.a2f3d50e ._77cdc67,',
'.b8812f16.a2f3d50e ._7b40dad,',
'.b8812f16.a2f3d50e ._8a693f3,',
'.b8812f16.a2f3d50e ._1d72f01,',
'.b8812f16.a2f3d50e .f3d18f6a,',
'.b8812f16.a2f3d50e ._3098d02 {',
'  background: transparent !important;',
'  backdrop-filter: none !important;',
'  -webkit-backdrop-filter: none !important;',
'}',
// Стекло применяем один раз — на корень сайдбара.
// Прозрачность — переменная --cuckoo-sidebar-opacity (0% — полностью прозрачно).
'.b8812f16.a2f3d50e {',
'  background: rgba(15, 18, 32, var(--cuckoo-sidebar-opacity)) !important;',
'  backdrop-filter: blur(var(--cuckoo-sidebar-blur)) saturate(140%) !important;',
'  -webkit-backdrop-filter: blur(var(--cuckoo-sidebar-blur)) saturate(140%) !important;',
'}',
// ========== 隐藏底部「Сгенерировано ИИ」免责声明 ==========
'._0fcaa63 {',
'  display: none !important;',
'}',
// ========== Модалка «Настройки» (и другие ds-modal) — матовое стекло ==========
'.ds-modal-content {',
'  background: rgba(15, 18, 32, 0.55) !important;',
'  backdrop-filter: blur(16px) saturate(140%) !important;',
'  -webkit-backdrop-filter: blur(16px) saturate(140%) !important;',
'}',
// Приглушаем фон-маску, чтобы под модалкой просвечивала страница
'.ds-modal-mask {',
'  background: rgba(0, 0, 0, 0.35) !important;',
'}',
// ========== Кнопка «Новый чат» в сайдбаре — матовое стекло ==========
'._5a8ac7a.a084f19e {',
'  background: rgba(15, 18, 32, 0.5) !important;',
'  backdrop-filter: blur(10px) saturate(140%) !important;',
'  -webkit-backdrop-filter: blur(10px) saturate(140%) !important;',
'  border: 1px solid rgba(139, 147, 255, 0.2) !important;',
'  border-radius: 12px !important;',
'}',
// ========== Рендер tool-блоков (cuckoo) — как в dsh-web-dev ==========
'.cuckoo-tool-block {',
'  margin: 8px 0;',
'  border: 1px solid rgba(139, 147, 255, 0.22);',
'  border-radius: 10px;',
'  background: rgba(15, 18, 32, var(--cuckoo-toolblock-opacity)) !important;',
'  backdrop-filter: blur(var(--cuckoo-toolblock-blur)) !important;',
'  -webkit-backdrop-filter: blur(var(--cuckoo-toolblock-blur)) !important;',
'  overflow: hidden;',
'  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
'}',
'.cuckoo-tool-header {',
'  display: flex; align-items: center; gap: 8px;',
'  padding: 8px 12px;',
'  cursor: pointer;',
'  user-select: none;',
'  font-size: 13px;',
'  color: #dde1ff;',
'  transition: background 0.15s;',
'}',
'.cuckoo-tool-header:hover { background: rgba(139, 147, 255, 0.09); }',
'.cuckoo-tool-chevron {',
'  display: inline-block; width: 12px; text-align: center;',
'  color: #8a90b8; font-size: 11px;',
'}',
'.cuckoo-tool-icon {',
'  display: inline-flex; align-items: center; justify-content: center;',
'  width: 16px; height: 16px;',
'  color: #a8afff;',
'  flex-shrink: 0;',
'}',
'.cuckoo-tool-icon svg {',
'  width: 16px !important; height: 16px !important;',
'  display: block;',
'  stroke: currentColor;',
'}',
'.cuckoo-tool-label { font-weight: 600; color: #a8afff; }',
'.cuckoo-tool-sep { color: #5d6280; }',
'.cuckoo-tool-file {',
'  color: #a7f3c0;',
'  font-family: "Consolas", "Cascadia Code", monospace;',
'  font-size: 12px;',
'  text-decoration: underline dashed rgba(167, 243, 192, 0.35);',
'  cursor: pointer;',
'}',
'.cuckoo-tool-block[data-expanded="true"] > .md-code-block {',
'  display: block !important;',
'  border-top: 1px solid rgba(255, 255, 255, 0.06);',
'  margin: 0 !important;',
'  border-radius: 0 !important;',
'}',
// ========== Стиль ошибки tool-блока ==========
'.cuckoo-tool-block.cuckoo-tool-error {',
'  border-color: rgba(255, 107, 122, 0.65) !important;',
'  background: rgba(60, 15, 22, 0.7) !important;',
'}',
'.cuckoo-tool-block.cuckoo-tool-error .cuckoo-tool-header {',
'  background: rgba(255, 107, 122, 0.1);',
'}',
'.cuckoo-tool-block.cuckoo-tool-error .cuckoo-tool-label {',
'  color: #ff8e9b !important;',
'}',
'.cuckoo-tool-block.cuckoo-tool-error .cuckoo-tool-chevron {',
'  color: #ff6b7a !important;',
'}',
'.cuckoo-tool-error-icon {',
'  color: #ff6b7a;',
'  font-size: 14px;',
'  margin-left: 4px;',
'}',
'.cuckoo-tool-error-msg {',
'  padding: 8px 12px;',
'  font-size: 12px;',
'  color: #ff9aa5;',
'  background: rgba(255, 107, 122, 0.1);',
'  border-top: 1px solid rgba(255, 107, 122, 0.3);',
'  white-space: pre-wrap;',
'  word-break: break-word;',
'  font-family: "Consolas", monospace;',
'}',
// Внутренний код-блок внутри tool-блока: фон/стекло по тем же переменным
'.cuckoo-tool-block .md-code-block,',
'.cuckoo-tool-block .md-code-block-banner-wrap,',
'.cuckoo-tool-block .md-code-block-banner,',
'.cuckoo-tool-block pre,',
'.cuckoo-tool-block code {',
'  background: rgba(15, 18, 32, var(--cuckoo-toolblock-opacity)) !important;',
'  backdrop-filter: blur(var(--cuckoo-toolblock-blur)) !important;',
'  -webkit-backdrop-filter: blur(var(--cuckoo-toolblock-blur)) !important;',
'}',
// Сам pre делаем прозрачным поверх фона контейнера — чтобы не дублировать
'.cuckoo-tool-block pre,',
'.cuckoo-tool-block code {',
'  background: transparent !important;',
'  backdrop-filter: none !important;',
'  -webkit-backdrop-filter: none !important;',
'}',
// ========== Мета-информация под ответом AI (время + токены) ==========
'.cuckoo-response-meta {',
'  display: inline-flex; align-items: center; gap: 6px;',
'  margin-top: 6px; padding: 3px 8px;',
'  font-size: 11px;',
'  color: #8a90b8;',
'  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
'  border-radius: 6px;',
'  user-select: none;',
'  opacity: 0.85;',
'}',
'.cuckoo-response-meta-item {',
'  display: inline-flex; align-items: center; gap: 4px;',
'}',
'.cuckoo-response-meta-item svg { display: block; }',
'.cuckoo-response-meta-sep { color: #5d6280; }',
// ========== RGB-переливание ника пользователя ==========
// Переливание включается, если у <body> нет класса `cuckoo-rgb-off`.
// Управляется настройкой rgbUsername из settings.json.
'body:not(.cuckoo-rgb-off) ._9d8da05 {',
'  background: linear-gradient(90deg, #ff4d4d, #ffa64d, #ffee4d, #4dff88, #4dd2ff, #8a4dff, #ff4dd2, #ff4d4d);',
'  background-size: 400% 100%;',
'  -webkit-background-clip: text;',
'  background-clip: text;',
'  -webkit-text-fill-color: transparent;',
'  color: transparent;',
'  animation: cuckoo-rgb-username 5s linear infinite;',
'  font-weight: 600;',
'}',
'@keyframes cuckoo-rgb-username {',
'  0% { background-position: 0% 50%; }',
'  100% { background-position: 400% 50%; }',
'}',
// ========== RGB-переливание кнопки «Повторить» (retry под ошибкой ответа) ==========
// Класс ds-button--warning стабильный (не хешированный). Ограничение .ds-message
// гарантирует, что не затронутся warning-кнопки в других местах (например, в настройках).
'.ds-message .ds-button--warning .ds-button__background,',
'.ds-message .ds-button--warning {',
'  background: linear-gradient(90deg, #ff4d4d, #ffa64d, #ffee4d, #4dff88, #4dd2ff, #8a4dff, #ff4dd2, #ff4d4d) !important;',
'  background-size: 400% 100% !important;',
'  animation: cuckoo-rgb-retry 5s linear infinite !important;',
'}',
'@keyframes cuckoo-rgb-retry {',
'  0% { background-position: 0% 50%; }',
'  100% { background-position: 400% 50%; }',
'}',
].join('\n');

module.exports = { OVERLAY_HTML, OVERLAY_CSS };
